### ISSUE TITLE
needs g++ 14 version or higher

### ISSUE THREAD

**Issue by Laiba9** [pranavdhawann/PDFInsightBot#1]
I got this error while build. Iam on windows and the max version of g++ I could install was 13.2,  Can you tell me which IDE should I use or how to get g++ 14 version on windows?
![Capture](https://github.com/pranavdhawann/PDFInsightBot/assets/138140152/213877df-e776-4370-b8ec-1cce1ba1f1c9)

**Comment by pranavdhawann** [comment]
I am using Visual Studio Code as my IDE. As for your issue, I think installing Microsoft Visual C++ Build Tools should fix it.

**Comment by Laiba9** [comment]
I did using MYSYS2 MINGW 64, but Still got 13.2 version. Can you guide me how can I download g++ 14 version?

**Comment by pranavdhawann** [comment]
Update and build all packages using the following commands in the MSYS2 bash shell.
pacman -Syu
pacman -S base-devel gcc vim cmake
