### ISSUE TITLE
chromadb issues

### ISSUE THREAD

**Issue by Ayesha-Muzamil** [pranavdhawann/PDFInsightBot#2]
<img width="551" alt="issue" src="https://github.com/pranavdhawann/PDFInsightBot/assets/119952909/a6547d46-893c-47d8-834f-25d491773721">
<img width="551" alt="issue" src="https://github.com/pranavdhawann/PDFInsightBot/assets/119952909/a6547d46-893c-47d8-834f-25d491773721">

**Comment by pranavdhawann** [comment]
run pip install -r requirements.txt first before running the program and it will run without any issue.
